#!/usr/bin/env python3

import argparse
import sys

from src.loqet.encryption_suite import generate_key, lock_file, unlock_file


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Tool for working local secrets")
    parser.add_argument("--keygen", action="store_true", help="Generate a new key")
    parser.add_argument("--vault", help="pass a file to vault")
    parser.add_argument("--unvault", help="Pass a vault file to unvault")
    args = parser.parse_args()

    arg_count = bool(args.keygen) + bool(args.vault) + bool(args.unvault)

    if arg_count == 0:
        parser.print_help()
        sys.exit()
    elif arg_count > 1:
        print("Accepts only one argument")
        parser.print_help()
        sys.exit()

    if args.keygen:
        if not os.path.exists(VAULT_KEY_FILE):
            print("Creating keyfile at {}".format(VAULT_KEY_FILE))
            generate_key()
        else:
            print("Keyfile already exists at {}. Doing nothing.".format(VAULT_KEY_FILE))

    if args.vault:
        vault(args.vault)

    if args.unvault:
        unvault(args.unvault)
